# docker compose for local env
version: "3.8"

services:
  honeypot:
    container_name: honeypot
    build:
      context: honeypot
      args:
        - RUNTIME_EMULATOR=1
    environment:
      - CONN_TIMEOUT_S=300
    ports:
      - '2222:22' # SSH
      - '9000:8080' # Lambda runtime emulator API

  honeyproxy:
    container_name: honeyproxy
    build:
      context: proxy
    environment:
      - LISTEN_PORT=22
      - CURRENT_IP=honeyproxy
      - AWS_S3_LOGGING_BUCKET=honeyshell-logs
      - AWS_LAMBDA_RIE_API=honeypot:8080
      - CONN_TIMEOUT_S=300
    ports:
      - '3333:22' # SSH proxy