# docker compose for local env
version: "3.8"

services:
  honeyproxy:
    container_name: honeyproxy
    networks:
      - honeyshell
    build:
      context: proxy
    environment:
      - LISTEN_PORT=22
      - CURRENT_IP=honeyproxy
      - AWS_S3_LOGGING_BUCKET=honeyshell-logs
      - LOCAL_CONTAINER=1
      - HONEYPOT_IMAGE_NAME=honeypot
      - DOCKER_NETWORK=honeyshell
      - CONN_TIMEOUT_S=300
      - IP_INFO_API_TOKEN=${IP_INFO_API_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '3333:22' # SSH proxy

networks:
  honeyshell:
    name: honeyshell