name: Publish Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy to S3
      run: aws s3 sync --delete --acl=public-read --cache-control max-age=7200 --metadata-directive REPLACE website/ s3://honeyshell-web/ 
    
    - name: Invalidate CloudFront
      run: aws cloudfront create-invalidation --distribution-id=EIT1XCF3DV5R4 --paths '/*'
